### ISSUE TITLE
不符合题意

### ISSUE THREAD

**Issue by shu295** [211706129/wang295#3]
对于看看钱包的操作，若输入如果，则看看钱包的内容未输出
![QQ图片20200211163829](https://user-images.githubusercontent.com/51659758/74221823-ee77a500-4ced-11ea-99d1-35bf28cbddf5.png)

**Comment by 211706129** [comment]
> 对于看看钱包的操作，若输入如果，则看看钱包的内容未输出
> ![QQ图片20200211163829](https://user-images.githubusercontent.com/51659758/74221823-ee77a500-4ced-11ea-99d1-35bf28cbddf5.png)

**Comment by 211706129** [comment]
我已经解决这个问题，代码已经改写完成
